stages:
  split:
    cmd: python3 src/data/load_and_split_data.py
    deps:
      - data/raw_data/raw.csv
    params:
      - split.test_size
      - split.random_state
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize:
    cmd: python3 src/data/normalisation.py
    deps:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    params:
      - normalisation.scaler
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv

  grid_search:
    cmd: python3 src/data/grid_search_param.py
    deps:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    params:
      - grid_search.n_estimators
      - grid_search.max_depth
      - grid_search.min_samples_split
      - grid_search.min_samples_leaf
    outs:
      - models/best_params.pkl

  evaluate:
    cmd: python3 src/models/evaluation.py
    deps:
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/trained_model.pkl
    params:
      - evaluate.metrics
    outs:
      - src/data/prediction.csv
    metrics:
      - metrics/scores.json:
          type: json
          cache: false
