split:
  test_size: 0.2
  random_state: 42

normalisation:
  scaler: "minmax"

grid_search:
  n_estimators: [100, 200, 300]
  max_depth: [10, 20, 30]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]

evaluate:
  metrics:
    - "mse"
    - "r2"
